### ISSUE TITLE
Sign phar with openssl

### ISSUE THREAD

**Issue by norberttech** [flow-php/flow#512]
Details: https://box-project.github.io/box/configuration/#the-private-key-key

This would let us add flow-php into [Phive](https://phar.io/)

**Comment by flavioheleno** [comment]
Hey, I've got a GHA workflow that does exactly that on a project that I maintain, I'm glad to adjust it for flow-php or you may do it yourself, your call :)

Here is the link to it: https://github.com/flavioheleno/watchr/blob/main/.github/workflows/release.yml

Just let me know what you rather do

**Comment by norberttech** [comment]
Hey @flavioheleno, 
Thanks for sharing! 
If by any chance you could help us with this, it would be more than welcome as we are busy with tons of other features. 
Anyway, thanks again, what you shared is already a huge help 🥰

**Comment by flavioheleno** [comment]
Oh wow, that was quick :)

I'm more than happy to work on a PR for this!

**Comment by norberttech** [comment]
I'm going to prepare secrets with `GPG_PRIVATE_KEY` and `GPG_PASSPHRASE` tomorrow so workflow can use them

**Comment by flavioheleno** [comment]
Awesome!
