### ISSUE TITLE
Fix broken examples

### ISSUE THREAD

**Issue by norberttech** [flow-php/flow#559]
Currently, not all examples can be executed, those that are designed to be loaded into phar would work, but there is no way to execute them through CLI. 
It would be nice to detect if a given example is loaded through Phar or executed directly and then decide if we should return DataFrame or execute DataFrame::run(). 
Another thing is autoloading, examples/bootstrap.php is no longer loading autoload.php since it assumes it will be executed through phar, here would be also good to detect if we are in the phar context, otherwise load regular autoload. 

We might also want to prepare a simple `run_examples.sh` or even `run_examples.php` script that would try to iterate over all examples and execute them one by one. Execution order is important here since some examples depend on the output from other examples.

**Comment by stloyd** [comment]
Fixed with #568 & related.
