### ISSUE TITLE
Issue GoogleSheetExtractor with empty sheet. 

### ISSUE THREAD

**Issue by scyzoryck** [flow-php/flow#639]
Hi! 

We found a weird edge case when using the `GoogleSheetExtractor` - when trying to load data from completely empty sheet the return of google response is `null`. 

```php
# vendor/flow-php/etl-adapter-google-sheet/src/Flow/ETL/Adapter/GoogleSheet/GoogleSheetExtractor.php:47
        /** @var Sheets\ValueRange $response */
        $response = $this->service->spreadsheets_values->get($this->spreadsheetId, $cellsRange->toString(), $this->options);
        /** @var array[] $values */
        $values = $response->getValues();
```
In reality it should be 

```php
# vendor/flow-php/etl-adapter-google-sheet/src/Flow/ETL/Adapter/GoogleSheet/GoogleSheetExtractor.php:47
        /** @var Sheets\ValueRange $response */
        $response = $this->service->spreadsheets_values->get($this->spreadsheetId, $cellsRange->toString(), $this->options);
        /** @var null|array[] $values */
        $values = $response->getValues();
```

I feel like the issue is on the Google repository side, but may it would be worth to handle this edgecase in the package as well? I can provide a fix if needed. 

Best, Marcin.

**Comment by norberttech** [comment]
Yeah, that's a weird behavior. 
A fix that would convert null into an empty array here would be very welcome unless you had a different idea of how to solve it?
