### ISSUE TITLE
Entry string value with space char

### ISSUE THREAD

**Issue by tetnobic** [flow-php/flow#742]
If in my row value, I have only this : " " 
Due to this : 
https://github.com/flow-php/etl/blob/11dd19d09b7b3f44606c97491439a8c1711dea38/src/Flow/ETL/Row/Factory/NativeEntryFactory.php#L41-L45

I go to the ->isJson(string $string) method with $string = ""
and so this : 
https://github.com/flow-php/etl/blob/11dd19d09b7b3f44606c97491439a8c1711dea38/src/Flow/ETL/Row/Factory/NativeEntryFactory.php#L306

crash with : **Uninitialized string offset 0** 

I think this check is not mandatory because already covered by the following test : 
https://github.com/flow-php/etl/blob/11dd19d09b7b3f44606c97491439a8c1711dea38/src/Flow/ETL/Row/Factory/NativeEntryFactory.php#L310-L313

PS: Same in isXML

**Comment by norberttech** [comment]
@tetnobic could you please confirm that your issue was resolved by #743?

**Comment by tetnobic** [comment]
> @tetnobic could you please confirm that your issue was resolved by #743?

Yes ! it works 
Thanks a lot
