### ISSUE TITLE
ETL Adapter CSV loader repeat headers

### ISSUE THREAD

**Issue by tetnobic** [flow-php/flow#748]
When use ETL Adapter CSV to write flow with the AwsS3Stream
the csv column headers is repeated every batch size

I think it's this line : 
https://github.com/flow-php/etl-adapter-csv/blob/230d8e40de9e26b7e7726bc6ee2fe395104c4255/src/Flow/ETL/Adapter/CSV/CSVLoader.php#L97

in case of aws s3 the file not exist during batch process (real write only at end)

Perhaps use 
$context->streams()->isOpen
instead of $context->streams()->exists

**Comment by norberttech** [comment]
Thanks for reporting this @tetnobic your suggestion worked, CSVLoader. should no longer write headers multiple times when saving files on remote filesystems.
