### ISSUE TITLE
Support for CamelCase columns

### ISSUE THREAD

**Issue by pabgaran** [flow-php/flow#768]
I have some tables with CamelCase names and columns (I can't change them). I've experienced troubles because when the query is builded, the columns are without quotes, like (Name, Surname, Email) and of course, the DB engine (postgres) is case-insesitive, so I get a error saying: "Column Name does not exists).

I've fixed this modifying the "concat" function on Flow\Doctrine\Bulk\Columns, simply like that:

`return '"'.\implode('"'.$separator.'"', $this->columns).'"';`

Now this work propely with CamelCase columns and lowercase columns, no errors.

Would be possible maybe add an option, to switch between quoted columns and not quoted?

Sorry if this is not the place to ask this question

**Comment by norberttech** [comment]
Could you prepare for me an example SQL that would create tables and add some columns into them, so I can reproduce this issue locally? 
This will help me verify if the solution that you proposed is good to implement and think about making it optional. 
Thanks!

**Comment by stloyd** [comment]
Should be fixed with #848
