### ISSUE TITLE
Add support for ZSTD compression

### ISSUE THREAD

**Issue by norberttech** [flow-php/flow#782]
Extension: https://github.com/kjdev/php-ext-zstd

**Comment by flavioheleno** [comment]
Hey, I'd like to give this a shot :)

Is this expected to be just a new ZstdSerializer or are there other areas to integrate as well? (or something completely different)

**Comment by norberttech** [comment]
hey @flavioheleno! 

So pretty much the goal is to implement it in Parquet [Codec](https://github.com/flow-php/flow/blob/1.x/src/lib/parquet/src/Flow/Parquet/ParquetFile/Codec.php) 

It's pretty much all about registering polyfill functions when the extension is not available (they can even throw an exception for now) and using them in the Codec class.

It should be very similar to: https://github.com/flow-php/snappy/blob/1.x/polyfill.php 

Additionally any tests that depends on zstd extension should be marked as skipped (unless you figure out a polifill that would do the same without installing extension)

**Comment by flavioheleno** [comment]
should Zstd get a folder under `flow/src/lib` to receive the polyfill? or should it go somewhere else?

**Comment by flavioheleno** [comment]
Once we get the PR to your standards, I'll be more than happy to do the same for #783 and #784

**Comment by norberttech** [comment]
I left some comments, let me know what are your thoughts, also don't hesitate to disagree/provide alternative solutions :)
