### ISSUE TITLE
Add support for LZ4 compression

### ISSUE THREAD

**Issue by norberttech** [flow-php/flow#783]
Extension: https://github.com/kjdev/php-ext-lz4

**Comment by flavioheleno** [comment]
Hey, the LZ4 support should be `Compressions::LZ4` or `Compressions::LZ4_RAW`?

I've stumbled upon [this doc](https://github.com/apache/parquet-format/blob/master/Compression.md) that states it should be `LZ4_RAW` and deprecate `LZ4` if possible.

I'll need some pointers on how to approach this :)

**Comment by norberttech** [comment]
> I've stumbled upon [this doc](https://github.com/apache/parquet-format/blob/master/Compression.md) that states it should be LZ4_RAW and deprecate LZ4 if possible.

hmm LZ4 is based on hadoop codec from what I see and LZ4_RAW is not, I think we would need to try if PHP extension for LZ4 would work with output from other libs that use LZ4 - it's mostly the compatibility issue. 

For now I think it's fine to make both go and use the same LZ4 functions provided by extensions
