### ISSUE TITLE
Double paragraph on the home page

### ISSUE THREAD

**Issue by andrewprofile** [flow-php/flow#999]
While reading the content on the project's home page in the "Consistent Memory Consumption" section, I noticed that the paragraph was duplicated. I have attached below which fragment it applies to. I would do a PR but I don't know which version is correct.

> But unfortunatelly it sounds easier than it is. The most common problem is lack of unified API for all data sources and memory management. Flow PHP solves this problem for you.

> But unfortunately, it sounds easier than it actually is. The most common problem lies in the lack of a unified API for all data sources and proper memory management. Flow PHP addresses this issue for you.

**Comment by norberttech** [comment]
fixed 👍
